#cloud-config
write_files:
  - path: /etc/NetworkManager/dispatcher.d/ifup-local
    content: |
      #!/bin/sh
      nm-online -q --timeout=30
      if ! ip route show default | grep -q "via ${vpc_gateway_ip}"; then
        /sbin/ip route add default via ${vpc_gateway_ip}
      fi
    permissions: '0755'

  - path: /etc/resolv.conf
    content: |
      # Generated by Cloud-init
      nameserver 185.12.64.2
      nameserver 185.12.64.1

runcmd:
  - dnf remove -y hc-utils #remove conflicting Hetzner auto-config
  - reboot
